export interface Song {
  albumId: number;
  id: number;
  name: string;
  spotify: string;
  deezer: string;
  apple: string;
  youtube: string;
  isActive: boolean;
  lyrics: string;
  credits: string;
}

export interface Album {
  id: number;
  name: string;
}

export const albums: Album[] = [
  { id: 5, name: "Lavovi" },
  {
    id: 4,
    name: "Noć Pod Zvijezdama",
  },
  {
    id: 3,
    name: "Balkanska Pravila",
  },
  {
    id: 2,
    name: "Ma Sretno 2012!",
  },
  { id: 1, name: "Kako Je Tako Je" },
];

export const albumSongs: Song[] = [
  {
    albumId: 1,
    id: 1,
    name: "Kako Je Tako Je",
    spotify: "",
    deezer: "",
    apple: "",
    youtube:
      "https://www.youtube.com/watch?v=ZivIQBOA9oM&list=OLAK5uy_lY1kFiWjBaebXsHZETA8H1ylQ4o6HGUls",
    isActive: false,
    lyrics: `Nisam ja tebi sudjen\novako sam sludjen\njos si dijete, a ja odvec\nna tugu osudjen dugo\nNisu tebi, mala zvijezdo\nove moje ruke gnijezdo\nidi leti svome jatu\nja cu bolu, starom bratu, tugo\nRef.\nKako je, tako je\nlazem te, lako je\nbez tebe, oko moje\nnije nikako\nIdi i ne placi\njer bol je najjaci\nod tebe daleko\nu meni prejako\n\nNemam ja kaput, lane\nda pod njega stanes\nnemam kisobran za snove\nkad bol na nas padne, tugo\nNisu tebi, mala zvijezdo\nove moje ruke gnijezdo\nidi leti svome jatu\nja cu bolu, starom bratu, tugo\nRef.\nRef. 2x`,
    credits: `Acoustic Guitar, Electric Guitar, Bouzouki – Petar Trumbetaš\nArranged By – Ognjan Radivojević\nBacking Vocals – Ivana Selakov\nDrum, Bass, Piano, Programmed By, Percussion – Ognjan Radivojević\nMusic By, Lyrics By – Bane Opačić`,
  },
  {
    albumId: 1,
    id: 2,
    name: "Ne Zovi Me",
    spotify: "",
    deezer: "",
    apple: "",
    youtube:
      "https://www.youtube.com/watch?v=5hOv1X8E0pw&list=OLAK5uy_lY1kFiWjBaebXsHZETA8H1ylQ4o6HGUls&index=2",
    isActive: false,
    lyrics: `Kriva si isto ko i ja, neka nas ljubav pobrise,\nmoja si bivsa i sve je bivse.\nNeka ti tuzno ne bude sto neko drugi sad je tu,\nna mojoj strani jastuka dise.\nNije to namjerno, nije nam sudjeno nikad ni bilo,\nal' ako tuzna si, nije vazno s'kim, to bi me ubilo.\n\nRef:\nNe zovi me tek da mi kazes da ti dobro ide s'njim\nNe zovi znam ja da me lazes ljubavi,\nNe zovi me,samo da bolje bude tvojoj sujeti,\nkad znas da sve za tebe ja cu podnijeti.\n\nKriva si isto ko i ja,sto sve na tugu mirise,\nmoja si bivsa,i sve je bivse.\nNek ti tuzno ne bude sto neko drugi sad je tu,\nna mojoj strani jastuka dise.\nNije to namjerno, nije nam sudjeno nikad ni bilo,\nal' ako tuzna si, nije vazno s'kim, to bi me ubilo.`,
    credits: `Acoustic Guitar, Electric Guitar, Keyboards, Programmed By – Dušan Alagić\nArranged By – Dušan Alagić\nBacking Vocals – Dragan Brnaš Fudo*, Ivana Čabraja, Jadranka Krištof\nBass – Dejan Antović\nDrum – Marko Kuzmanović\nElectric Guitar – Miloš Vuksanović\nMusic By, Lyrics By – Bane Opačić`,
  },
  {
    albumId: 1,
    id: 3,
    name: "Ne Govori",
    spotify: "",
    deezer: "",
    apple: "",
    youtube: "https://www.youtube.com/watch?v=LVdgJk2JUTU",
    isActive: false,
    lyrics: `Nisam ovo ja, nisi ovo ti\nnisi ona koju znam\nprevisok je zid, predubok je vir\nvec sam dugo s tobom sam\nI cemu rijeci\nbilo je dana kad smo mogli pricati\ni cemu rijeci\nsamo ces moje greske priznati\nRef.\nNe govori, sve je to za nas\nsto te nema kada si mi najpotrebnija\nubija me svaka tvoja laz\nidi s drugim, budi srecnija\nSta smo ovo mi, sta to postali\nporusili sve do dna\nsvaki pogled je kap sto prelije\ncutimo, al' sve se zna\nNe govori, sve je to za nas\nkada vise nisam ti ni na kraj pameti\npukli smo i reci to na glas\nsve cu ovo lakse podnjeti`,
    credits: `Acoustic Guitar, Electric Guitar, Mandolin, Keyboards – Dušan Alagić\nArranged By – Dušan Alagić\nBacking Vocals – Ivana Selakov\nDrum – Dejan Momčilović\nMusic By, Lyrics By – Bane Opačić`,
  },
  {
    albumId: 1,
    id: 4,
    name: "Jer Sam Tvoj Kad Nema Ko",
    spotify: "",
    deezer: "",
    apple: "",
    youtube:
      "https://www.youtube.com/watch?v=ErH2EfH_tYM&list=OLAK5uy_lY1kFiWjBaebXsHZETA8H1ylQ4o6HGUls&index=3",
    isActive: false,
    lyrics: `Jer sam tvoj kad nema ko\nlijek za lose ljubavi\nStezem rijec u zubima\njer nijedne nisi vrijedna\nglumim nas pred ljudima\nlaz tako ocigledna\nI opet sve precutacu\nsprati ponos suzama\ntvoju bol progutacu\nbol sa tudjih usana\n\nJer sam tvoj kad nema ko\nlijek za lose ljubavi\nda te mrzim ne znam to\na znam da trebalo bi\nJer sam tvoj kad nema ko\nlijek za lose ljubavi\nevo priznajem ti to\nne znam da te ostavim\nI opet sve precutacu\nsprati ponos suzama\ntvoju bol proguracu\nbol sa tudjih usana\nJer sam tvoj kad nema ko\nlijek za lose ljubavi\nda te mrzim ne znam to\na znam da trebalo bi\nJer sam tvoj kad nema ko\nlijek za lose ljubavi\nevo priznajem ti to\nne znam da te ostavim`,
    credits: `Acoustic Guitar, Electric Guitar, Piano – Dušan Alagić\nArranged By – Dušan Alagić\nBacking Vocals – Darija Hodnik, Dragan Brnaš Fudo*, Ivana Čabraja, Jadranka Krištof\nBass – Dejan Antović\nDrum – Marko Kuzmanović\nMusic By, Lyrics By – Bane Opačić`,
  },
  {
    albumId: 1,
    id: 5,
    name: "Da Me Malo Hoće",
    spotify: "",
    deezer: "",
    apple: "",
    youtube:
      "https://www.youtube.com/watch?v=lYreqSI20uA&list=OLAK5uy_lY1kFiWjBaebXsHZETA8H1ylQ4o6HGUls&index=5",
    isActive: false,
    lyrics: `Ej, noci, imas li stanice\nu ovom vozu od snova\nil' opet vozis do granice\nmog bola\nZnam da joj nista moje ne treba\nal' ipak sve joj dajem\notkad je nemam, nit' putujem\nnit' stajem\nGdje ljubim, sve susi\ngdje sanjam, tu ne svane\ngde taknem, sve rusim\nona jos drzi moj svet da ne padne\nRef.\nHej, da me malo hoce\npa da mi dodje\nk'o nekad, nezvana\nHej, ne bi nista radje\nte usne sladje\nod prvih tresanja\nHej, da me malo hoce\npa da me prodje\nsto boli odavno\nHej, da je vidim samo\nza dobre dane\nda nazdravimo\ni zapevamo\n\nZnam da joj nista moje ne treba\nal' ipak sve joj dajem\notkad je nemam, nit' nestajem\nnit' trajem\nGde ljubim, sve susi\ngde sanjam, tu ne svane\ngdje taknem, sve rusim\nona jos drzi moj svijet da ne padne`,
    credits: `Arranged By – Dušan Alagić\nBacking Vocals – Ivana Selakov\nBouzouki – Petar Trumbetaš\nGuitar – Miloš Vuksanović\nGuitar, Keyboards, Programmed By – Dušan Alagić\nMusic By, Lyrics By, Vocals [Featuring] – Bane Opačić`,
  },
  {
    albumId: 1,
    id: 6,
    name: "Na Dlanu",
    spotify: "",
    deezer: "",
    apple: "",
    youtube:
      "https://www.youtube.com/watch?v=_9S7BG-EN_s&list=OLAK5uy_lY1kFiWjBaebXsHZETA8H1ylQ4o6HGUls&index=6",
    isActive: false,
    lyrics: `To je trn koji dusu mi para\nparce srca odlama,\ntrag na licu covjeka sto stari\nkad ga stigne sudbina...\nZelja nek' se nocas prolije\nkao vino istinu sto nosi,ove noci besane.\n\nIma dana kad se svega sjetim ja,\nzivim zivot kad se sve zaboravlja,\nal' na dlanu uvjek isto pisace\nnova ljubav staru ne brise\nznaj, srce vjecno pamtice.\n\nSa tvojih usana nek' teku rjeci\nprobudi srce pospano,\nzagrli me rukama hladnim\nza mene bice dovoljno...\nZelja nek' se nocas prolije\nkao vino istinu sto nosi,ove noci besane.\n\nIma dana kad se svega sjetim ja,\nzivim zivot kad se sve zaboravlja,\nal' na dlanu uvjek isto pisace,\nnova ljubav staru ne brise\nznaj, srce vjecno pamtice.`,
    credits: `Arranged By – Bojan Dragojević, Dušan Alagić\nBacking Vocals – Ana Marković (2), Ivana Andrejić, Miloš Vuksanović, Tamara Komazec\nBass – Branko Isaković\nDrum – Marko Kuzmanović\nLead Guitar – Miloš Vuksanović\nMusic By, Lyrics By, Arranged By – Aleksandar Mitrović\nPercussion – Aleksandar Mitrović\nViolin, Electric Guitar, Acoustic Guitar, Keyboards, Programmed By, Mandolin – Dušan Alagić`,
  },
  {
    albumId: 1,
    id: 7,
    name: "Da Me Nemaju Neke Bolje",
    spotify: "",
    deezer: "",
    apple: "",
    youtube:
      "https://www.youtube.com/watch?v=JzYk2ev5f9g&list=OLAK5uy_lY1kFiWjBaebXsHZETA8H1ylQ4o6HGUls&index=7",
    isActive: false,
    lyrics: `Tu sam pred teskim vratima\nod tvoje ljubavi jos je prosim\nzivim za tren tvog pogleda\nk'o zig mi ostavi da ga nosim\nZnam da me neces\nal' ne das drugoj da me zavoli\nda odglumis bol i zaplaces\ntek da mene zaboli\nRef. 2x\nDa me nemaju neke bolje\nsve si moje, dobro sebi uzela\nvise nemaju sta da vole\nsve je tvoje i u tom si uspjela\nTu si u svakoj rijeci\nu svakom dodiru sto zaboli\ntajna, od svih te cuvam\nal' lako otkriju da te volim\nZnam da me neces\nal' ne das drugoj da me zavoli\nda odglumis bol i zaplaces\ntek da mene zaboli\nRef. 2x`,
    credits: `Acoustic Guitar, Electric Guitar – Petar Trumbetaš\nArranged By – Ognjan Radivojević\nBacking Vocals – Ivana Selakov\nDrum, Bass, Piano, Programmed By, Percussion – Ognjan Radivojević\nMusic By, Lyrics By – Bane Opačić`,
  },
  {
    albumId: 1,
    id: 8,
    name: "Ne Kradi Srce Od Lopova",
    spotify: "",
    deezer: "",
    apple: "",
    youtube:
      "https://www.youtube.com/watch?v=5Q0c-5ivhkc&list=OLAK5uy_lY1kFiWjBaebXsHZETA8H1ylQ4o6HGUls&index=9",
    isActive: false,
    lyrics: `Isti smo, od drugih krademo sne\nza grijeh nasa ljubav je maska, zar ne\nI znam o tebi dobro bas sve\nda volis i varas za noc ili dve\nKao ja, srce uvek drzim zakljucano\nsto da se pretvaramo ledena\nRef.\nNe, ne kradi srce od lopova\ngde bas mi na put da jedno drugom stanemo\nludo radi ritam tih bokova\nmozda jedno na drugo ipak nocas padnemo\nIsti smo, od drugih krademo sne\nza grijeh nasa ljubav je maska, zar ne\nI znam, srce uvek drzis zakljucano\nsto da se pretvaramo ledena\nRef. 3x`,
    credits: `Accordion – Željko Vasić\nArranged By – Bojan Dragojević, Dušan Alagić, Miloš Vuksanović\nBacking Vocals – Lexington*, Suzana Dinić\nBass – Emilijan Cupa\nDrum – Dejan Momčilović\nGuitar – Dušan Alagić, Miloš Vuksanović\nMusic By, Lyrics By – Bane Opačić\nProgrammed By, Keyboards – Bojan Dragojević, Dušan Alagić`,
  },
  {
    albumId: 1,
    id: 9,
    name: "Kad Kreneš",
    spotify: "",
    deezer: "",
    apple: "",
    youtube:
      "https://www.youtube.com/watch?v=3hUahs7LKNs&list=OLAK5uy_lY1kFiWjBaebXsHZETA8H1ylQ4o6HGUls&index=10",
    isActive: false,
    lyrics: `Necu te pustiti\nsa golom istinom\nu moje srce\nda udjes nezvana\nNecu razjumeti\nda ti je pretesko\nsto si za noc\nme s drugim prodala\nNemoj cekati jutro\nsve da promjeni\nko da oprosti\nbol kad ljubav zamjeni\nRef.\nKad krenes\nidi sto prije, ne budi ljude\nhtjela si to, neka ti bude\nne ostavljaj ni jednu ruznu rec\nni jednu uvredu\nKad krenes\nidi sto prije, jer vec nas nema\nnek' sam ti bol za sva vremena\nne dam ti svoj ponos i poraz ponovo\nza tvoju pobjedu\nNecu te pustiti\nod tudjih usana\nna dlanu mom'\nda dusu odmoris\nIdi i ostavi\nbar malo ponosa\nkad za sobom\nvrata zatvoris`,
    credits: `Acoustic Guitar, Electric Guitar, Keyboards – Dušan Alagić\nArranged By – Dušan Alagić\nBacking Vocals – Dragan Brnaš Fudo*, Ivana Čabraja, Jadranka Krištof\nBass – Dejan Antović\nDrum – Marko Kuzmanović\nElectric Guitar – Miloš Vuksanović\nMandolin, Lute – Aleksandar Sedlar\nMusic By, Lyrics By – Bane Opačić`,
  },
  {
    albumId: 1,
    id: 10,
    name: "Anđele Moj Mali (Akustik)",
    spotify: "",
    deezer: "",
    apple: "",
    youtube:
      "https://www.youtube.com/watch?v=s92L_MNIbWM&list=OLAK5uy_lY1kFiWjBaebXsHZETA8H1ylQ4o6HGUls&index=8",
    isActive: false,
    lyrics: `Nikad nisam umeo\nda ti bol sa bolom vratim, moja tugo\nnocas tu sam ponovo\nbar pozovi me da svratim, necu dugo\n\nPodsjeti me da smo zajedno\nod tvojih bih se lazi napio\njer odavno sam ovaj zivot svoj\nja u tvoje ruke stavio\n\nRef.\nCija si to, andjele moj mali\nko te nocas tako dobru kvari\nko ti je to malo nevjere ugostio\ncija si to, andjele moj mali\nopet neku dobru laz podvali\nvrati se, ma znas sta bih ti sve oprostio\n\nNikad nisi umjela\nda me imas, da me cuvas, moja tugo\nnekom drugom bolja si\na ja gori poslije tebe svakoj drugoj\n\nRef. 2x`,
    credits: `Arranged By – Dušan Alagić, Miloš Vuksanović\nBacking Vocals – Dragan Brnaš Fudo*, Ivana Čabraja, Jadranka Krištof\nLead Guitar – Miloš Vuksanović\nMusic By, Lyrics By – Bane Opačić\nPiano, Acoustic Guitar – Dušan Alagić`,
  },
  {
    albumId: 1,
    id: 11,
    name: "Anđele Moj Mali (Stara Verzija)",
    spotify: "",
    deezer: "",
    apple: "",
    youtube:
      "https://www.youtube.com/watch?v=UU94IFFQajs&list=OLAK5uy_lY1kFiWjBaebXsHZETA8H1ylQ4o6HGUls&index=11",
    isActive: false,
    lyrics: `Nikad nisam umeo\nda ti bol sa bolom vratim, moja tugo\nnocas tu sam ponovo\nbar pozovi me da svratim, necu dugo\n\nPodsjeti me da smo zajedno\nod tvojih bih se lazi napio\njer odavno sam ovaj zivot svoj\nja u tvoje ruke stavio\n\nRef.\nCija si to, andjele moj mali\nko te nocas tako dobru kvari\nko ti je to malo nevjere ugostio\ncija si to, andjele moj mali\nopet neku dobru laz podvali\nvrati se, ma znas sta bih ti sve oprostio\n\nNikad nisi umjela\nda me imas, da me cuvas, moja tugo\nnekom drugom bolja si\na ja gori poslije tebe svakoj drugoj\n\nRef. 2x`,
    credits: `Acoustic Guitar, Electric Guitar, Keyboards, Mandolin – Dušan Alagić\nArranged By – Dušan Alagić\nBacking Vocals – Jelena Mitić, Miloš Vuksanović, Suzana Dinić\nBass – Dejan Antović\nElectric Guitar – Miloš Vuksanović\nMusic By, Lyrics By – Bane Opačić\nPercussion – Vladan Popović-Pop\nSaxophone – Gabor Bunford*`,
  },
  {
    albumId: 1,
    id: 12,
    name: "Da Me Malo Hoće (Remix)",
    spotify: "",
    deezer: "",
    apple: "",
    youtube: "https://youtu.be/HBqXGTgLz-Y?si=W5b7ivWep7wbh-Vf",
    isActive: false,
    lyrics: `Ej, noci, imas li stanice\nu ovom vozu od snova\nil' opet vozis do granice\nmog bola\nZnam da joj nista moje ne treba\nal' ipak sve joj dajem\notkad je nemam, nit' putujem\nnit' stajem\nGdje ljubim, sve susi\ngdje sanjam, tu ne svane\ngde taknem, sve rusim\nona jos drzi moj svet da ne padne\nRef.\nHej, da me malo hoce\npa da mi dodje\nk'o nekad, nezvana\nHej, ne bi nista radje\nte usne sladje\nod prvih tresanja\nHej, da me malo hoce\npa da me prodje\nsto boli odavno\nHej, da je vidim samo\nza dobre dane\nda nazdravimo\ni zapevamo\n\nZnam da joj nista moje ne treba\nal' ipak sve joj dajem\notkad je nemam, nit' nestajem\nnit' trajem\nGde ljubim, sve susi\ngde sanjam, tu ne svane\ngdje taknem, sve rusim\nona jos drzi moj svijet da ne padne`,
    credits: `Arranged By – Adnan Alagić, Erik Morgan\nMusic By, Lyrics By, Vocals [Featuring] – Bane Opačić`,
  },
  {
    albumId: 2,
    id: 13,
    name: "Dobro Da Nije Veće Zlo",
    spotify: "",
    deezer: "",
    apple: "",
    youtube:
      "https://www.youtube.com/watch?v=UYzrTbpiyv4&list=OLAK5uy_nLoHTP6vEnE-c4YOpZ302ZTHmWeetnlHo",
    isActive: false,
    lyrics: `Dobro dosla u moj grad, kako si\nko i onih dana jos lijepa si\nsta su ove godine bez mene ti donjele\n\nKazes zivot ti je bas potaman\nimas klince, kola i velik' stan\na zna li da te nasmije onako do suza\n\nKazes nije to moja stvar\ni da sam tvoj najveci promasaj\n\nRef. 2x\nDobro da nije neko vece zlo\novo je srce moje vec prezivjelo\ndobro je da si dobro, bilo cija da si\ndobro je, neka,\nneka, neka si\n\nRef. 4x`,
    credits: `Arranged By – Alek Aleksov\nMusic By, Lyrics By – Bane Opačić`,
  },
  {
    albumId: 2,
    id: 14,
    name: "U Srce Udaraj",
    spotify: "",
    deezer: "",
    apple: "",
    youtube:
      "https://www.youtube.com/watch?v=lSXqFc0dYPE&list=OLAK5uy_nLoHTP6vEnE-c4YOpZ302ZTHmWeetnlHo&index=2",
    isActive: false,
    lyrics: `Rekla si mi zauvek tvoja\na na pragu sad' trag je tvojih koraka\njos juce bila si moja\nBoze kakava zabluda\n\nProbao sam sve, ali ne ide\ntugom okovan, ne zaboravljam\nda ljubav gubi jaz, to radis najbolje\n\nRef.\nU srce udaraj, zbog tebe stalo je\nkazem sve si moje, kazes malo je\ntvom' je srcu draza\nsaka puna bisera\n\nU srce udaraj, ma pristajem na sve\nzivot bih ti dao, kazes malo ti je\na kom' ces mila moja\nkada prva suza krene\n\nBoli dusa, kako i nebi\nna zivot ja sam ljut,\njer ti me lako ostavljas\nPitam se kako je tebi\nkada sebe pogledas\n\nProbao sam sve, ali ne ide\ntugom okovan, ne zaboravljam\nda ljubav gubi jaz, to radis najbolje\n\nRef.\n\nRef.`,
    credits: `Arranged By – Alek Aleksov\nLyrics By – Ksenija Mijatović\nMusic By – S. Simić Kamba*`,
  },
  {
    albumId: 2,
    id: 15,
    name: "Smrti Se Ne Bojim",
    spotify: "",
    deezer: "",
    apple: "",
    youtube: "https://youtu.be/iwyhwLgztZo?si=OtGx3op71G4t4xmR",
    isActive: false,
    lyrics: `Nijedna bol\nme ne bi toliko boljela\nkao saznanje, da si\nkraj mene drugog voljela\nNijedna rijec\nme ne bi toliko ubila\nkao saznanje\nda si drugog ljubila\nRef.\nSmrtno te volim, smrti se ne bojim\nkao za zivot za tebe se borim\njer ako odes, ne znam znas li to\nbez tebe dan ne bih zivio\nNe bi nijedno istina\ntako boljela\nkao saznanje, da si\nkraj mene drugog voljela\nRef.\nZelena trava i luda glava\nistinu krije, istinu zna\nbez tebe ja nisam ja\nnisam ja, nisam ja\nRef.`,
    credits: `Arranged By – Dača Mag*\nLyrics By – Miladin Bogosavljević\nMusic By, Arranged By – G. Ratković Rale*`,
  },
  {
    albumId: 2,
    id: 16,
    name: "Uvrijedi Me",
    spotify: "",
    deezer: "",
    apple: "",
    youtube: "https://youtu.be/0oja1iO6Oi8?si=2WmNx1Gu1ae03vgw",
    isActive: false,
    lyrics: `Nedostupna si\nopet noci ove\na srce jos te trazi\ni upomoc zove\nI cini mi se da su svi\noko mene ljudi zli\nuvijek kada sa mnom nisi ti\ntako trebas mi\nja znam da ti si\nproslost al' jos nisi\nRef.\nUvrijedi me kad te molim\nda prestanem da te volim\nuvrijedi me al' toliko\nda postanes meni niko\nUvrijedi me dok jos mozes\nsamo naprijed bez problema\nda znam da sam dusu dao\nonoj koja duse nema\nNedostizni su\nopet moji snovi\njer sreca moja s tobom\nmorem tuge plovi\nI cini mi se da su svi\noko mene ljudi zli\nuvijek kada sa mnom nisi ti\ntako trebas mi\nja znam da ti si\nproslost al' jos nisi\nRef.\nRef.`,
    credits: `Arranged By – Dača Mag*\nLyrics By – Miladin Bogosavljević\nMusic By, Arranged By – G. Ratković Rale*`,
  },
  {
    albumId: 2,
    id: 17,
    name: "Pijane Usne",
    spotify: "",
    deezer: "",
    apple: "",
    youtube: "https://youtu.be/JeLy5VQIuDI?si=Z5eVquFk-6PUPgRC",
    isActive: false,
    lyrics: `Gdje te nadju ovi dani\nda l\` te stara tuga rani\nmeni vise od zivota\ntugo falis, tugo falis...\nDogodine doci neces\na ni one trece zime\nuvenuce srce moje\ntvoje srce nepamti me\n\nRef: 2x\nPijane usne ne lazu\nvjeruj o meni sve sto ti kazu\nda kockam se i gubim sve\nzbog te ljubavi nevjerne\n\nJos u kraju gdje smo stara\nbol ko uvjek osmjeh vara\nkome jutro smjehom budis\nmjesto dara, mjesto dara\nDogodine doci neces\na ni one trece zime\nuvenuce srce moje\ntvoje srce nepamti me\n\nRef: 2x\nPijane usne ne lazu\nvjeruj o meni sve sto ti kazu\nda kockam se i gubim sve\nzbog te ljubavi nevjerne\n\nPijane usne ne lazu\nvjeruj o meni sve sto ti kazu\nda kockam se i gubim sve\nsamo zbog tebe, zbog tebe`,
    credits: `Arranged By – Dušan Alagić\nMusic By, Lyrics By – Bane Opačić`,
  },
  {
    albumId: 2,
    id: 18,
    name: "Miris Karmina",
    spotify: "",
    deezer: "",
    apple: "",
    youtube: "https://youtu.be/KaMvb_6gv9w?si=ZIzth0pvQyI-zEHx",
    isActive: false,
    lyrics: `Miris tvog karmina\nu vene me puca\nnavucen sam sad\nvino prosipam\n\nI ratujem sa svima\nda nocas te nadjem\nprevrnucu grad\nmoja prokleta\n\nNocas negdje naci cu te\nidem da upropastim se\nka tebi krenucu\na sutra kajacu se\n\nZnam te...\nznam da pratis mi trag\nmrzis, sto ipak jos drag\njer ti i ja jedno smo drugom\nk'o droga, i moram da osjetim ja\n\nREF.\nMiris tvog karmina\nu vene me puca\nnavucen sam sad\nvino prosipam\n\nI ratujem sa svima\nda nocas te nadjem\nprevrnucu grad\nmoja prokleta\n\nMoja prokleta 3x\n\nNegde naci cu te\nidem da upropastim se\njer ti i ja jedno smo drugom\nk'o droga, i moram da osjetim ja\n\nREF.\n\nMoja prokleta 3x\n\nREF.`,
    credits: `Music By, Lyrics By – Svetlana Vuković\nMusic By, Lyrics By, Arranged By – Dušan Alagić`,
  },
  {
    albumId: 2,
    id: 19,
    name: "Samo Ostani Tu",
    spotify: "",
    deezer: "",
    apple: "",
    youtube: "https://youtu.be/zwWb19RzTeQ?si=LcNo4hLgIjPstWzX",
    isActive: false,
    lyrics: `Cuvam te, ne dam te nikom\nja samo s tobom zelim sve\ncuvam te, ne dam te nikom\nni da mi sve u zivotu stane\nCuvaj me, ne daj me nikom\nja tebe necu nikada\ncuvaj me, ne daj me nikom\nsve sto sam ja, sve ti pripada\nRef.\nDa ti se svet srusi ceo\nmog sveta deo dacu\nsamo ostani tu\ni kad ne znas gde ces\nni kako do srece\nja znacu, samo ostani tu\nsamo ostani tu\nCuvam te, ne dam te nikom\nsve sto sam ja, sve ti pripada\nRef. 2x\nSamo ostani tu\n(2x)`,
    credits: `Arranged By – Alek Aleksov\nFeaturing – Biljana Pećić\nLyrics By – Mira Mijatović*\nMusic By, Lyrics By – Miloš Vuksanović`,
  },
  {
    albumId: 2,
    id: 20,
    name: "Soba Bez Morala",
    spotify: "",
    deezer: "",
    apple: "",
    youtube: "https://youtu.be/LtvwmwVt7Ok?si=okpItHxzcXN4aErM",
    isActive: false,
    lyrics: `Nece bol,\nNi minut\nDa okasni,\nTu je i ono\nPropalo,\nDa upropasti,\nNe bi ti\nNikog u srce\nPustila\nKad sam tu prije\nVremena,opet\nZakasnim\nZnao sam ja oduvijek\nSta i ko si\nLjubav kao igru\nNosis\nNemas kajanja,\nZa takve kao ja..\n\nRefren:\nMa cija da si bila\nIz koje postelje\nSe budila\nU pola noci dodji\nRaznesi usnama\nDo ludila\nMa cija da si\nZnas me\nKad to pozelis\nUvijek imas me\nU sobi bez morala\nCekam da kupis,\nI da prodas me\nZa neku tudju laz,\nPa ti\nTo najbolje znas...\n\nNe bi ti,\nNikog u srce\nPustila\nI kad sam tu\nPrije vremena\nUvijek zakasnim,\nZnao sam ja oduvijek\nSta i ko si\nLjubav kao igru\nNosis\nNemas kajanja,\nZa takve kao ja..\n\nRefren 2x`,
    credits: `Arranged By – Dušan Alagić\nMusic By, Lyrics By – Bane Opačić`,
  },
  {
    albumId: 2,
    id: 21,
    name: "Bol Je Uvijek Ista",
    spotify: "",
    deezer: "",
    apple: "",
    youtube: "https://youtu.be/5HEt2GMo_5s?si=sXvbZzWb6WkbSb5t",
    isActive: false,
    lyrics: `Kom' si svoju kosu prosula u krilo\nda bar znam da dobro si\nlakse bi mi bilo bez nas\nZivim ove dane, ne nadam se boljem\ni jos sebi oprostim i sto nije moje\nda l' znas, da l' znas\nRef.\nDa, bol je uvijek ista za sve sto tuguju\nnoc je preduga za sve sto samuju\nu ranu rana se lako zarije\nbez tebe zivot, zivot nije\nBol je uvijek ista za sve sto tuguju\nnoc je preduga za sve sto samuju\nranu rana se lako zarije\nbez tebe ovaj zivot, sta mi je\nKom' na dlanu nocas zaspala si, vilo\nda bar znam da srecna si\nlakse bi mi bilo bez nas\nZivim ove dane, ne nadam se boljem\ni jos sebi oprostim i sto nije moje\nda l' znas, da l' znas\nRef.2x`,
    credits: `Arranged By – Alek Aleksov\nMusic By, Lyrics By – Bane Opačić`,
  },
  {
    albumId: 2,
    id: 22,
    name: "2012!",
    spotify: "",
    deezer: "",
    apple: "",
    youtube: "https://youtu.be/ohvF2gucvwI?si=lRHA3MAo5gi0IwIe",
    isActive: false,
    lyrics: `Ostavila ti si tragove\nprstiju na srcu mom\nprosula prasinu zvezdanu\nsjajnu u mraku tom\nDa mogu da prepoznam\ntvoj dodir poslije svega\njednom kad nam se lica promjene\njednom kada prodju godine\nRef.\nEvo ide, evo gazi, 2012.\nljudi kazu da ce biti propast svijeta\na nas dvoje bas je briga\nu krevetu za planetu\nmi cemo se voljeti i na\nnekom drugom svijetu\nOstavila ti si ljubav\nu srcu za citav vijek\nostaces u meni\nza sva vremena, toliko tek\nDa mogu da prepoznam\ntvoj dodir poslije svega\njednom kad nam se lica promjene\njednom kada prodju godine\nRef.`,
    credits: `Arranged By – Dača Mag*\nLyrics By – Miladin Bogosavljević\nMusic By, Arranged By – G. Ratković Rale*, Perica Simonović`,
  },
  {
    albumId: 3,
    id: 23,
    name: "Pile",
    spotify: "",
    deezer: "",
    apple: "",
    youtube:
      "https://www.youtube.com/watch?v=63eEuPl7ZTc&list=OLAK5uy_lE3rKNQ2oceYMWGXDMEDMCGp0S_Dv23Dg",
    isActive: false,
    lyrics: `Na ove ruke ne padaj, svilo\nstrah me da te ne pokidam\na ti se, pile, pod moje krilo\npodvuces kada ne gledam\nk'o dar tvoj osmijeh docekam\n\nRef.\nDa je tvojih godina\novom srcu umornom\nda te voli kako zna\nal' mi nije sudjeno\n\nDa je tvoga proljeca\nmojoj zimi ledenoj\nkasno za me rodjena\na ja niciji k'o tvoj\n\nNikoga nemas i nikog nemam\nza dusu dusu vezala\nal' kako da te zivotu kradem\ntek si mu poletjela\na meni krila umorna\n\nRef. 2x`,
    credits: `Arranged By – Alek Aleksov (tracks: 1, 2, 10, 13, 14), Dušan Alagić (tracks: 3, 4, 6, 8, 12)\nDesign – Stanislav Zakić\nLyrics By – Bane Opačić (tracks: 1, 2, 3, 6, 8, 10 to 14), Dejan Praščević (tracks: 4, 9)\nMastered By – James Cruz\nMusic By – Bane Opačić (tracks: 1, 2, 3, 8, 10 to 14)\nMusic By, Arranged By – Goran Ratković Rale* (tracks: 4, 9)`,
  },
  {
    albumId: 3,
    id: 24,
    name: "Ako Se Ne Vidimo",
    spotify: "",
    deezer: "",
    apple: "",
    youtube: "https://youtu.be/UIbORX7Irgk?si=3phd2xG2RTrZHFxA",
    isActive: false,
    lyrics: `Sanjao sam, opet si tu\nsa usana krades poljubac prvi\nopet gledas me, k'o prvi put\ni sapuces mi, do jutra me ljubi\nSlikama vratim prosle dane\ni onaj osmijeh na licu tvom'\nkako za minut zivot stane\npamti bar to\nRef.\nAko se ne vidimo, znaj, da jedina si\nostala si, zivote, cekanja vrijedna\nne zelim ja tudje noci, druge oci\njedino srce da mjenjam\nZnaj, jedina si\nostala si, zivote, cekanja vrjedna\nne zelim ja tudje noci, druge oci\njedino srce da mjenjam\nu ovo nece ni jedna\nRef.\nZauvijek znaj, da jedina si\nostala si zivote cekanja vredna\nne zelim ja tudje noci, druge oci\njedino srce da mjenjam\nRef.\nU ovo nece ni jedna`,
    credits: `Arranged By – Alek Aleksov (tracks: 1, 2, 10, 13, 14), Dušan Alagić (tracks: 3, 4, 6, 8, 12)\nDesign – Stanislav Zakić\nLyrics By – Bane Opačić (tracks: 1, 2, 3, 6, 8, 10 to 14), Dejan Praščević (tracks: 4, 9)\nMastered By – James Cruz\nMusic By – Bane Opačić (tracks: 1, 2, 3, 8, 10 to 14)\nMusic By, Arranged By – Goran Ratković Rale* (tracks: 4, 9)`,
  },
  {
    albumId: 3,
    id: 25,
    name: "Treznili Me Prijatelji",
    spotify: "",
    deezer: "",
    apple: "",
    youtube: "https://youtu.be/4wlR11wMB7c?si=Hn6IIY81J7biVyjY",
    isActive: false,
    lyrics: `Trijeznili me prijatelji moji\nispod tvoga prozora\nja se pijan sjetim da te volim\ntrijezan ne zaboravljam\n\nNikog' ne pitam o tebi\nznam da lagace, svejedno\nosmijeh ne skidam, a zivot nemam\notkad nismo zajedno\n\nRef.\nNisam poslije nas nikom' dobar, moje milo\nodkud ova laz, ovaj zivot, sta se zbilo\nsamo bjezim ti od ljubavi\nnisam poslije nas nikom' srce dao\ni jos stojim tu, gdje sam s tobom stao\nsamo bjezim ti od ljubavi\n\nTrijeznile te drugarice tvoje\nispred moga ulaza\nnekada smo bili pravih dvoje\no tome sad nijednog dokaza\n\nNikom' ne pricaj o meni\nznam da lagaces, svejedno\nosmijeh ne skidas, a zivot nemas\notkad nismo zajedno\n\nRef. 2x`,
    credits: `Arranged By – Alek Aleksov (tracks: 1, 2, 10, 13, 14), Dušan Alagić (tracks: 3, 4, 6, 8, 12)\nDesign – Stanislav Zakić\nLyrics By – Bane Opačić (tracks: 1, 2, 3, 6, 8, 10 to 14), Dejan Praščević (tracks: 4, 9)\nMastered By – James Cruz\nMusic By – Bane Opačić (tracks: 1, 2, 3, 8, 10 to 14)\nMusic By, Arranged By – Goran Ratković Rale* (tracks: 4, 9)`,
  },
  {
    albumId: 3,
    id: 26,
    name: "Dođi Ove Noći",
    spotify: "",
    deezer: "",
    apple: "",
    youtube: "https://youtu.be/vL33eBLgj1U?si=ViQ9barURM-Cxyj8",
    isActive: false,
    lyrics: `Ti si nedodirljiva\nali svako zna ja rijecima lovim\npa visim ispod prozora\nza pocetak da ti zavjesu sklonim\nStihovi su moji fini, kao biseri\nprovjeri da l' su pravi, samo pozuri\njer je pjesnik nocas krenuo u lov\na ti znas, da lovac nema krov\nRef. 2x\nDodji ove noci, do mog gnjezda\nnabracu ti puno krilo zvijezda\nsamo mi pokazi rukom koje\ni bice, i bice samo tvoje\nZvizdim, a ne bih da se zna kome zvizdim ja\nal' zvizduk svi cuju\npa jedni, kazu koji car, drugi koja stvar\na reci me psuju\nBriga me za prve, druge, trece i za sve\nodgovori mi, al' odgovori mi sto prije\njer je pjesnik nocas krenuo u lov\na ti znas, da lovac nema krov\nRef. 2x`,
    credits: `Arranged By – Alek Aleksov (tracks: 1, 2, 10, 13, 14), Dušan Alagić (tracks: 3, 4, 6, 8, 12)\nDesign – Stanislav Zakić\nLyrics By – Bane Opačić (tracks: 1, 2, 3, 6, 8, 10 to 14), Dejan Praščević (tracks: 4, 9)\nMastered By – James Cruz\nMusic By – Bane Opačić (tracks: 1, 2, 3, 8, 10 to 14)\nMusic By, Arranged By – Goran Ratković Rale* (tracks: 4, 9)`,
  },
  {
    albumId: 3,
    id: 27,
    name: "Potraži Me",
    spotify: "",
    deezer: "",
    apple: "",
    youtube: "https://youtu.be/E31bcPr2gr8?si=TkdgcHap3TNXLCcW",
    isActive: false,
    lyrics: `Nije ti vjernost u genima\nlako bi svakog zamjenila\nali ja sam tu da razumijem te\n\nNemas ti srce u grudima\nkad' si me nevinog ubila\nali cak i to ja razumijem\n\nJer nije ovo s'nama laz\nma mozes da se otimas\nal' u tudjem zagrljaju hladno je\n\nRef.\nPotrazi me kad sloboda ti dosadi\nkada greh ti se osladi\nnemoj stati, samo se meni vrati\n\nBicu tu dam me izdas\nbicu tu sve da priznas\nbicu tu kada sreca ti kaze ne\nda zagrlim te\n\nNemas ti savjest ni najmanje\nda bi dozivjela kajanje\nal' ja sam tu da razumijem sve\n\nNemas ni hrabrost u ocima\nda bi se samnom suocila\nali cak i to ja razumijem\n\nJer nije ovo s'nama laz\nma mozes da se otimas\nal' u tudjem zagrljaju hladno je\n\nRef.\n\nRef.2x`,
    credits: `Arranged By – Marko Cvetković (3)\nLyrics By – Jelena Trifunović\nMusic By – Bojan Vasić (2)`,
  },
  {
    albumId: 3,
    id: 28,
    name: "Prišla",
    spotify: "",
    deezer: "",
    apple: "",
    youtube: "https://youtu.be/k72tmgWdj_U?si=0iinLEITxx9IsSnC",
    isActive: false,
    lyrics: `Krenuo sam malo da se odmorim na more\nvozio sam samac, cjelo drustvo mi je dole\nstigao sam kasno, oni vec u punom gasu\nodmorio bih malo, oni, hajde na terasu\n\nRef.\nPrisla je sama, sta sam mogao ja\nkada htjela je sve da mi da\nhtjela sve da mi da\nnad nama sija mjesecina\nja bih i sutra, ona kaze mi\nznas, ja sam zauzeta\n\nSunce nas je probudilo u glavi nam je zvecka\npa nismo rekli Bokiju da mala ima decka\nko i da mu kaze kada previse se pilo\nma hajde da ga pitamo, kako ti je bilo\n\nRef.\n\nNe pakujem srce kad se pakujem za more\njer se ljetnje ljubavi prebrzo izgore\nvidi sad i ova mala s plaze mi se smjeska\nma samo pazi dobro da i ona nema decka\n\nRef. 2x`,
    credits: `Arranged By – Lexington*\nMusic By – A. Potapenko*`,
  },
  {
    albumId: 3,
    id: 29,
    name: "Nezaboravna",
    spotify: "",
    deezer: "",
    apple: "",
    youtube: "https://youtu.be/IXXMF7xoT0E?si=I429YXGJKuh8PQKH",
    isActive: false,
    lyrics: `Svakim jutrom\nnovi dan se budi\nidu dalje ljudi\nkog briga sta se zbilo\n\nSamo ja jos po\nsjecanju tumaram\nsvoju srecu stvaram\nod neceg sto je bilo\n\nGradske price\ntise su i tise\ni vec odavno vise\n\nRef.\nNiko me ne pita za tebe\nbijese jednom ljubav davna\nal' osmijeh tvoj jos srce grebe\njos si moja nezaboravna\n\nMnogi nadju nacin\nda prebole\niznova da vole\nvrijeme sve lance kida\n\nSamo ja jos tu\nu mjestu stojim\nuspomene brojim\nu ova cet'ri zida\n\nRef. 2x`,
    credits: `Arranged By – Peđa Blizanac*\nMusic By, Lyrics By – Nenad Blizanac*`,
  },
  {
    albumId: 3,
    id: 30,
    name: "Nemiru Moj",
    spotify: "",
    deezer: "",
    apple: "",
    youtube: "https://youtu.be/QG3m-N9xSFA?si=_Fpnb0phvzfBOgyL",
    isActive: false,
    lyrics: `Ne znam poslije nas ni desno ni lijevo\nnekad minut dva zaboravim te\nrekla si probaj s drugom i pokusavam evo\nal' prava ljubav nikada ne umire\n\nRef. 2x\nPozovi\nnemiru moj, isto sam tvoj\nkao i pr'je, samo je tuga veca za broj\ntako je to, kad ne da se ljubav za ljubav\n\nPozovi\n\nNe znam poslije nas gdje legnem, da svanem\nkraj tudjih usana, ne mogu, ne\nidem, jer nikad nisam ja tamo gdje stanem\nprava ljubav nikada ne umire\n\nRef. 4x`,
    credits: `Music By – Dejan Praščević`,
  },
  {
    albumId: 3,
    id: 31,
    name: "Balkanska Pravila",
    spotify: "",
    deezer: "",
    apple: "",
    youtube: "https://youtu.be/gXROYyQix3s?si=5OidgbotJIl-g6QP",
    isActive: false,
    lyrics: `Cesto sjednem sam\nna nasu klupu staru\nkad dragu ne mogu\nja zagrlim gitaru\nPa onda mol po mol\npolako lomim bol\na on je zilav lik\npa izlazi k'o pobjednik\nRef.\nDobro vece svima\nostavljacima\njos vise ostavljenima\nUvijek ima dima\nako covjek suzom\ngasi zar u ocima\nHajdemo ruke nek'\npodigne svako\nko je bar jednom\nzbog ljubavi plak'o\nsreca i tuga\nsve je za covjeka\nHajdemo ruke nek'\npodigne svako\nko je bar jednom\nzbog ljubavi plak'o\nprekrsio kao ja\nbalkanska pravila\nK'o lopov najveci\nsuza se prikrade\nal' ja je ne pustim\nmuskarci to ne rade\nRef.\nRef.`,
    credits: `Arranged By – Ogi Radivojević*`,
  },
  {
    albumId: 3,
    id: 32,
    name: "Godinama",
    spotify: "",
    deezer: "",
    apple: "",
    youtube: "https://youtu.be/j2hzaQo4Y-E?si=8UxaGgT3lPPfqgLw",
    isActive: false,
    lyrics: `Gdje si to godinama bila\nod sebe krila\nsve dok vodu ti je pilo\nda ne umjes ni da se budis\nni da zaspis od kad\nme nije tu bilo\nNisam ja vise onaj stari\nkoji kvari sitnicom velike stvari\nnaucio sam svoje skole\nhtio bolje\nti si to bolje, ustvari\nRef.\nGodinama bojim ovaj zivot siv\ngodinama nisam ni mrtav ni ziv\nsvaka mi je kriva i svakoj sam kriv\njer nikad nisi ti, u svakoj nisi ti\nGodinama kraj ociju sljep\nmolim da je zivot barem tebi ljep\ndobrodosla ako zelis ostati\na ako odes, znaj\nneko ce zauvjek cekati\nneko ce zauvjek cekati\nAko se pitas mozda\nja sam ti sve oprostio\ni sto sebi nisi mogla\ni sto sebi nisi mogla\nRef.`,
    credits: `Arranged By – Alek Aleksov (tracks: 1, 2, 10, 13, 14), Dušan Alagić (tracks: 3, 4, 6, 8, 12)\nDesign – Stanislav Zakić\nLyrics By – Bane Opačić (tracks: 1, 2, 3, 6, 8, 10 to 14), Dejan Praščević (tracks: 4, 9)\nMastered By – James Cruz\nMusic By – Bane Opačić (tracks: 1, 2, 3, 8, 10 to 14)\nMusic By, Arranged By – Goran Ratković Rale* (tracks: 4, 9)`,
  },
  {
    albumId: 3,
    id: 33,
    name: "Ne Znam Čija Si",
    spotify: "",
    deezer: "",
    apple: "",
    youtube: "https://youtu.be/gXROYyQix3s?si=b04PjuAnEfjhVZb7",
    isActive: false,
    lyrics: `Gdje su noci, javo\nskrile nebo plavo\ncrni su mi snovi\nhajde me pozovi\n\nDuga jesen siva\njos si rana ziva\nbole dani ovi\nhajde me pozovi\n\nRef.\nJa ne znam cija si\nk'o sto moja si\na tudja staris\n\nI ne znam koji su novi datumi\nkoje slavis\ni ne znam pravu rijec\nda kazem kako mi nocas falis\n\nDa bar na minut, dva\nsrce pored mog srca stavis\nja ne znam cija si\n\nRef.`,
    credits: `Arranged By – Alek Aleksov (tracks: 1, 2, 10, 13, 14), Dušan Alagić (tracks: 3, 4, 6, 8, 12)\nDesign – Stanislav Zakić\nLyrics By – Bane Opačić (tracks: 1, 2, 3, 6, 8, 10 to 14), Dejan Praščević (tracks: 4, 9)\nMastered By – James Cruz\nMusic By – Bane Opačić (tracks: 1, 2, 3, 8, 10 to 14)\nMusic By, Arranged By – Goran Ratković Rale* (tracks: 4, 9)`,
  },
  {
    albumId: 3,
    id: 34,
    name: "Nina",
    spotify: "",
    deezer: "",
    apple: "",
    youtube: "https://www.youtube.com/watch?v=JxfyTXyItfQ",
    isActive: false,
    lyrics: `Nina, moja stara ljubavi\njedan mi zivot malo da zaboravim\nkazu da ljubav snagu daje\nmene je ubila\njos te u svakom vjetru trazim\ngdje si se izgubila\nKaplje sa krovova stara nostalgija\nmoja ti luka bila tjesna\npa si isplovila\nkazu da ljubav snagu daje\nmene je ubila\njos te u svakom vjetru trazim\ngdje si se izgubila\nRef.\nMoj brod sada plovi\ngdje je kosa njena\nNina samo ti ga mozes\nspasiti od stjena\nmolitva za jednu zvjezdu\niz daljina, da se meni vratis\nRef.\nNina moja stara ljubavi\ncjeli mi zivot malo da zaboravima`,
    credits: `Featuring – Tribal Band (2)`,
  },
  {
    albumId: 3,
    id: 35,
    name: "Dve Case (feat. Tribal Band)",
    spotify: "",
    deezer: "",
    apple: "",
    youtube: "https://youtu.be/Z9Xt_dShbZo?si=2GazEzLJKWjrNgw1",
    isActive: false,
    lyrics: `Dve case uvek lakse prebole tugu\nJos mi na kozi gori trag njenih usana\nza druge dusa k'o u lance mi vezana\n'Zalud pamet kaze, njoj se ne nadaj\nkad u snove dodje mi zvana, nezvana\nRef.\nDve case uvek lakse prebole tugu\nneka su srecu nasle selice na jugu\ndve case i sve flase, ovo je mesto nase\ndve case i dva srca meni i mom' drugu\nProlaze dani, nju ni tren ne zaboravljam\njos po svakom, ko je zna, je pozdravljam\n'Zalud pamet kaze, kreni, ne cekaj\ntamo gdje je ona stala nastavljam\nRef. 2x`,
    credits: `Arranged By – Alek Aleksov (tracks: 1, 2, 10, 13, 14), Dušan Alagić (tracks: 3, 4, 6, 8, 12)\nDesign – Stanislav Zakić\nLyrics By – Bane Opačić (tracks: 1, 2, 3, 6, 8, 10 to 14), Dejan Praščević (tracks: 4, 9)\nMastered By – James Cruz\nMusic By – Bane Opačić (tracks: 1, 2, 3, 8, 10 to 14)\nMusic By, Arranged By – Goran Ratković Rale* (tracks: 4, 9)`,
  },
  {
    albumId: 3,
    id: 36,
    name: "Donesi",
    spotify: "",
    deezer: "",
    apple: "",
    youtube: "https://youtu.be/rY1nngCSNuY?si=21PQ_epHIquLbLRf",
    isActive: false,
    lyrics: `Sta je sve, lijepa moja, moglo\niz ovih ruku u te ruke na dar\niz ovog srca u to srce, prosla stvar\nNeke stjene kapi slome\ni ovu nasu ljubav su sitnice\nsto manje govorim o tome\nsve mi je lakse da te gledam u lice\na da ne umrem, zbog nas ne umrem\nRef.\nDonesi stari smjeh iz dobrih godina\nbar jedno budjenje u jutra nemirna\nnove ljubavi neka pricekaju\nDonesi prvi snjeg i nasa proljeca\nonda lazi me da se ne sjecas\nsta si bila tad'\na sta si danas drugim ljudima\nsamo to vidi, pa idi\ni ne nadaj se cudima\nRef. 2x`,
    credits: `Arranged By – Alek Aleksov (tracks: 1, 2, 10, 13, 14), Dušan Alagić (tracks: 3, 4, 6, 8, 12)\nDesign – Stanislav Zakić\nLyrics By – Bane Opačić (tracks: 1, 2, 3, 6, 8, 10 to 14), Dejan Praščević (tracks: 4, 9)\nMastered By – James Cruz\nMusic By – Bane Opačić (tracks: 1, 2, 3, 8, 10 to 14)\nMusic By, Arranged By – Goran Ratković Rale* (tracks: 4, 9)`,
  },
  {
    albumId: 4,
    id: 37,
    name: "Ljetne Kiše",
    spotify: "",
    deezer: "",
    apple: "",
    youtube: "https://youtu.be/bTLCVfJwl78?si=R2fCjbqfLhlDGf9A",
    isActive: false,
    lyrics: `Noc je pocela bez plana\nna pola flase zavrsena\nsa mnom ljudi puni mana\na ti si tako savrsena\nSamo da mi otvoris ta vrata\nu grudima zakljucana\nna pola daha sam od straha\ndo ludila\nTi i ja\nne treba nama nista drugo\nnikada\nnisam ja volela tako ludo\nRef.\nZagrli i poljubi me sada\nostani bar nocas sa mnom do kraja\ngromovi nek' lome nebo mog grada\nnek' padaju ljetne kise po nama\nRef. 2x\nZagrli\nostani\ngromovi\nnek' padaju ljetne kise po nama\nRef.`,
    credits: `Arranged By – Alek Aleksov (tracks: 1, 2, 6, 9, 11, 13, 15, 17), Dušan Alagić (tracks: 3, 4, 7, 8, 14), Marko Cvetković (3) (tracks: 5, 10)\nDesign – Stanislav Zakić\nLyrics By – Bane Opačić (tracks: 2, 4, 6, 11, 13, 14, 15, 17), Jelena Trifunović (tracks: 5, 7, 10), Marina Tucaković (tracks: 8, 18)\nMastered By – Streaky\nMusic By – Bane Opačić (tracks: 2, 6, 11, 13, 15, 17), Bojan Vasić (2) (tracks: 8, 10), Miloš Vuksanović (tracks: 4, 11, 14)\nPhotography By – Miloš Nadaždin`,
  },
  {
    albumId: 4,
    id: 38,
    name: "Ja Te Srećom Častim",
    spotify: "",
    deezer: "",
    apple: "",
    youtube: "https://youtu.be/AZFzpSvOS7k?si=Nlb6duZX1TCS79J4",
    isActive: false,
    lyrics: `Ostao mi na reveru kap parfema\nu ruci s tvoje crne kose dijadema\nk'o uvijek kad te smori uloga dobre zene\ndodjes po malo mene\nKraj njega ti je zivot sigurica\nprijaju ti sva ta lazno nasmijana lica\nkad ti je do zivota, pozovi svoga skota\nda stari film premota\nRef.\nKad ogrebe te svila, ti samo pozovi\nu jeftinoj sobi su najskuplji snovi\nja bit cu zauvijek tvoj zlocin iz strast\nti plati sve drugo, a ja te srecom castim\nOstala je izguzvana posteljina\nna podu popijena boca vina\ntvoj miris svud po sobi, jutro i kafa jedna\nistina lazi vrijedna\nRef. 2x\nRef.`,
    credits: `Arranged By – Alek Aleksov (tracks: 1, 2, 6, 9, 11, 13, 15, 17), Dušan Alagić (tracks: 3, 4, 7, 8, 14), Marko Cvetković (3) (tracks: 5, 10)\nDesign – Stanislav Zakić\nLyrics By – Bane Opačić (tracks: 2, 4, 6, 11, 13, 14, 15, 17), Jelena Trifunović (tracks: 5, 7, 10), Marina Tucaković (tracks: 8, 18)\nMastered By – Streaky\nMusic By – Bane Opačić (tracks: 2, 6, 11, 13, 15, 17), Bojan Vasić (2) (tracks: 8, 10), Miloš Vuksanović (tracks: 4, 11, 14)\nPhotography By – Miloš Nadaždin`,
  },
  {
    albumId: 4,
    id: 39,
    name: "Navučen Na Tvoje Usne",
    spotify: "",
    deezer: "",
    apple: "",
    youtube: "https://youtu.be/ouWuRHWTm7w?si=3VG-t5cMdYq65kdJ",
    isActive: false,
    lyrics: `I nocas dodje mi da\nsrce zivo spalim\npred svima kazem - dobro sam\nlazima se hvalim\nA oci navikle su se na mrak\ntvoga srca cujem puls\nidem kao manijak\ntrazim te jer nemam kud\nRef.\nNavucen sam na tvoje usne\ndodji sada\nk'o onih dana jos u meni\nzivi nada\nDa mi se vrati nase ljeto\nnasa zima\nsrecan sam samo dok me imas\ndok te imam\nI nocas tjesan mi je grad\ntjesna dusa\ngdje god da odem\nneko nasu pjesmu pusta\nRef. 3x`,
    credits: `Arranged By – Alek Aleksov (tracks: 1, 2, 6, 9, 11, 13, 15, 17), Dušan Alagić (tracks: 3, 4, 7, 8, 14), Marko Cvetković (3) (tracks: 5, 10)\nDesign – Stanislav Zakić\nLyrics By – Bane Opačić (tracks: 2, 4, 6, 11, 13, 14, 15, 17), Jelena Trifunović (tracks: 5, 7, 10), Marina Tucaković (tracks: 8, 18)\nMastered By – Streaky\nMusic By – Bane Opačić (tracks: 2, 6, 11, 13, 15, 17), Bojan Vasić (2) (tracks: 8, 10), Miloš Vuksanović (tracks: 4, 11, 14)\nPhotography By – Miloš Nadaždin`,
  },
  {
    albumId: 4,
    id: 40,
    name: "Gdje Mi Je Pamet Bila",
    spotify: "",
    deezer: "",
    apple: "",
    youtube: "https://youtu.be/hlLImvMhnGQ?si=aXNEPH_vDLrUFqAE",
    isActive: false,
    lyrics: `Ovih dana sve mi po zlu\nni da stanem ni da krenem\novih dana falis mi tu\nsamo ne smijem da spomenem\nOvih dana zivim po svom\nkoga ljubim gubim za dan\nti si list u sjecanju mom\nkoji nikad ne otvaram\nRef.\nGdje mi je pamet bila\nda te slomljenog srca ostavim\nnisam vidio tad\nnisam, srece mi\nGdje mi je pamet bila\nda se okrenem i ne pozdravim\nti zaboravila\na ja cu s grijehom tim da ostarim\nOvih dana isto sam lud\ntrazim neke pjesme stare\novih dana vidim te svud\nneki se snovi ne ostvare\nRef. 4x`,
    credits: `Arranged By – Alek Aleksov (tracks: 1, 2, 6, 9, 11, 13, 15, 17), Dušan Alagić (tracks: 3, 4, 7, 8, 14), Marko Cvetković (3) (tracks: 5, 10)\nDesign – Stanislav Zakić\nLyrics By – Bane Opačić (tracks: 2, 4, 6, 11, 13, 14, 15, 17), Jelena Trifunović (tracks: 5, 7, 10), Marina Tucaković (tracks: 8, 18)\nMastered By – Streaky\nMusic By – Bane Opačić (tracks: 2, 6, 11, 13, 15, 17), Bojan Vasić (2) (tracks: 8, 10), Miloš Vuksanović (tracks: 4, 11, 14)\nPhotography By – Miloš Nadaždin`,
  },
  {
    albumId: 4,
    id: 41,
    name: "Ne Postoji Razlog (Den Thelo Epafi)",
    spotify: "",
    deezer: "",
    apple: "",
    youtube: "https://youtu.be/gKuqwJX3mA4?si=P_YiBnDLN78pHYbI",
    isActive: false,
    lyrics: `Sve je bilo k'o da sanjam\nkrenuli smo jednog dana\nbuducnost i ja\nGodine su prolazile\npune smijeha i idile\nali jedan dan\nMoje srce iznenada\nse okrenulo\ni u istom trenu\nsve se preokrenulo\nRef.\nNe postoji razlog\nda se tebi vratim\ni da poslije svega ponovo\nza tobom patim\nNe postoji razlog\nda u proslost gledam\nda se pred ljepotom tvojom\nkao nekad predam\nNisi mogla ti\nda me zavolis\na ja jos ne mogu\nda zaboravim\nSve je bilo kako treba\nali k'o da bol mi ne da\nda nastavim sam\nRef.`,
    credits: `Arranged By – Alek Aleksov (tracks: 1, 2, 6, 9, 11, 13, 15, 17), Dušan Alagić (tracks: 3, 4, 7, 8, 14), Marko Cvetković (3) (tracks: 5, 10)\nDesign – Stanislav Zakić\nLyrics By – Bane Opačić (tracks: 2, 4, 6, 11, 13, 14, 15, 17), Jelena Trifunović (tracks: 5, 7, 10), Marina Tucaković (tracks: 8, 18)\nMastered By – Streaky\nMusic By – Bane Opačić (tracks: 2, 6, 11, 13, 15, 17), Bojan Vasić (2) (tracks: 8, 10), Miloš Vuksanović (tracks: 4, 11, 14)\nPhotography By – Miloš Nadaždin`,
  },
  {
    albumId: 4,
    id: 42,
    name: "Smij Se",
    spotify: "",
    deezer: "",
    apple: "",
    youtube: "https://youtu.be/qFY-EPN8lEM?si=diZybVPhCuntpWMG",
    isActive: false,
    lyrics: `Sta ce nam rijeci koje kasne\nsto dodju samo da raznesu pepeo\nsta ce nam ljubav koja splasne\nja s pola srca nikad nisam volio\nBudi nocas jos jednom hrabra za mene\nRef.\nVidim ti u oku onaj sjaj, k'o zadnji pokusaj\nda nas vrijeme ne obrise\nnaprijed i nazad ne gledaj, pogledaj u sad\nsmij se, suza je bilo previse\nSta ce mi krila kada padnem\nda me sete da sam nekad letela\nna cije pola sad da stanem\nja nikad nisam nas na dvoje delila\nBudi nocas jos jednom hrabar za mene\nRef. 2x`,
    credits: `Arranged By – Alek Aleksov (tracks: 1, 2, 6, 9, 11, 13, 15, 17), Dušan Alagić (tracks: 3, 4, 7, 8, 14), Marko Cvetković (3) (tracks: 5, 10)\nDesign – Stanislav Zakić\nLyrics By – Bane Opačić (tracks: 2, 4, 6, 11, 13, 14, 15, 17), Jelena Trifunović (tracks: 5, 7, 10), Marina Tucaković (tracks: 8, 18)\nMastered By – Streaky\nMusic By – Bane Opačić (tracks: 2, 6, 11, 13, 15, 17), Bojan Vasić (2) (tracks: 8, 10), Miloš Vuksanović (tracks: 4, 11, 14)\nPhotography By – Miloš Nadaždin`,
  },
  {
    albumId: 4,
    id: 43,
    name: "Sprava",
    spotify: "",
    deezer: "",
    apple: "",
    youtube: "https://youtu.be/SVJat_RshIs?si=gGT8RUdoBJDdLVXL",
    isActive: false,
    lyrics: `Sam u cet'ri zida\nblokirani prilazi\niz stana proseta mi tjelo\ndusa mi ne izlazi\nCekam tebe da se javis\nuloge da podjelis\nu ovoj seriji o nama\nigram koga pozelis\nJedan dan ti treba heroj\nsutra vise ne, zreo covjek\nsto u trenu dijete postane\ngrubi ljubavnik sto umije\nnjezno da ti cuva sne\nSve mogu, ali jedno ne\nRef.\nTi bi malo da se sjetis\nmeni da se javis\nda ti budem sprava ta\nkoju pokrenes na dugme\nda ti bude blizu\nuvijek kad ti zatrebam\nTi bi malo da se sjetis\nmeni da se javis\nda ti budem sprava ta\nkoju pokrenes na dugme\nkad ti fali ljubav\nsve od sebe da ti dam\nali jedno znam\nja nikad necu biti taj\nRef. 2x`,
    credits: `Arranged By – Alek Aleksov (tracks: 1, 2, 6, 9, 11, 13, 15, 17), Dušan Alagić (tracks: 3, 4, 7, 8, 14), Marko Cvetković (3) (tracks: 5, 10)\nDesign – Stanislav Zakić\nLyrics By – Bane Opačić (tracks: 2, 4, 6, 11, 13, 14, 15, 17), Jelena Trifunović (tracks: 5, 7, 10), Marina Tucaković (tracks: 8, 18)\nMastered By – Streaky\nMusic By – Bane Opačić (tracks: 2, 6, 11, 13, 15, 17), Bojan Vasić (2) (tracks: 8, 10), Miloš Vuksanović (tracks: 4, 11, 14)\nPhotography By – Miloš Nadaždin`,
  },
  {
    albumId: 4,
    id: 44,
    name: "Čarobna",
    spotify: "",
    deezer: "",
    apple: "",
    youtube: "https://youtu.be/7wpnysU8ojw?si=PLvpy7akAieyP6WT",
    isActive: false,
    lyrics: `Ne treba tebi, duso, nocas magija\nni carobni napitak da poludim ja\ncarobna kada si cijela tako\ncarobna, sta mi jos treba\nTvoja je kisa meni\nsusu donjela\nk'o camac od papira\nsad me nose nemiri\nnije to ludilo ni magija\njer to si ti\nRef.\nTu sam da ispunim sto zamislis\nda slusam te kad god se pozalis\nne pitaj s kim sam i gdje\nja brze stici cu tu od poruke\nTu sam da sklonim s neba oblake\nlako k'o s tvoga lica uvojke\nreci da nisam skroz lud i da je obostrano\ni bice nam vedro i suncano\nNa stotinu se zena usput pojavi\nal' samo jedna od njih cudo napravi\ncarobna samo je jedna k'o ti\ncarobna za sva vremena\nRef.`,
    credits: `Arranged By – Alek Aleksov (tracks: 1, 2, 6, 9, 11, 13, 15, 17), Dušan Alagić (tracks: 3, 4, 7, 8, 14), Marko Cvetković (3) (tracks: 5, 10)\nDesign – Stanislav Zakić\nLyrics By – Bane Opačić (tracks: 2, 4, 6, 11, 13, 14, 15, 17), Jelena Trifunović (tracks: 5, 7, 10), Marina Tucaković (tracks: 8, 18)\nMastered By – Streaky\nMusic By – Bane Opačić (tracks: 2, 6, 11, 13, 15, 17), Bojan Vasić (2) (tracks: 8, 10), Miloš Vuksanović (tracks: 4, 11, 14)\nPhotography By – Miloš Nadaždin`,
  },
  {
    albumId: 4,
    id: 45,
    name: "Noć Pod Zvijezdama",
    spotify: "",
    deezer: "",
    apple: "",
    youtube: "https://youtu.be/TpXDvIVjtkQ?si=lzrYBRxkWZWITw5m",
    isActive: false,
    lyrics: `Jos pamtim nase puteve i staze\nsnove o buducnosti i sreci\nnista nismo imali osim ljubavi\nkako smo se ludo voljeli\nRekla si da bices vjecno moja\nda ne maris za svilu i zlato\nja ostadoh a ti ode, mila\nodveli te i zlato i svila\nali ne brini, ako ti zatrebam\nRef.\nLako cemo, samo pozovi\nkada ti dosade zurke i koteli\nkada u sjaju tom ostanes sama\nvrati se starim stazama\nLako cemo, samo pozovi\nkada kraj njega sruse ti se snovi\nkada u sjaju tom ostanes sama\njos cuvam za nas noc pod zvijezdama\nJos nisam nikom priznao da boli\nrana koja nosi tvoje ime\nprava ljubav nikad ne postane dim\nnaucis da zivis s time\nRef.`,
    credits: `Arranged By – Alek Aleksov (tracks: 1, 2, 6, 9, 11, 13, 15, 17), Dušan Alagić (tracks: 3, 4, 7, 8, 14), Marko Cvetković (3) (tracks: 5, 10)\nDesign – Stanislav Zakić\nLyrics By – Bane Opačić (tracks: 2, 4, 6, 11, 13, 14, 15, 17), Jelena Trifunović (tracks: 5, 7, 10), Marina Tucaković (tracks: 8, 18)\nMastered By – Streaky\nMusic By – Bane Opačić (tracks: 2, 6, 11, 13, 15, 17), Bojan Vasić (2) (tracks: 8, 10), Miloš Vuksanović (tracks: 4, 11, 14)\nPhotography By – Miloš Nadaždin`,
  },
  {
    albumId: 4,
    id: 46,
    name: "Ako Voliš Me",
    spotify: "",
    deezer: "",
    apple: "",
    youtube: "https://youtu.be/cv9Ex2s1s3E?si=_TRn9uT4_36QjXV0",
    isActive: false,
    lyrics: `Jos si moje pice posljednje\na tolko proslo je godina\nteske noci provodim bez nas\nda zivot mi je laz i Bog to zna\nMi tako brzo smo ka sreci hodali\nod sebe samih smo veci postali\nRef.\nAko volis me jos kao tebe ja\nmali znak pogledom mi daj\nnije vazno da l' si ljubav ili grijeh\njos od tebe srce ne odustaje\nJos se tijelo budi umorno\ni sve je sumorno kad nisi tu\ntvoja slika postala je noz\nto ubilo me skroz, al' uzalud\nRef. 4x`,
    credits: `Arranged By – Alek Aleksov (tracks: 1, 2, 6, 9, 11, 13, 15, 17), Dušan Alagić (tracks: 3, 4, 7, 8, 14), Marko Cvetković (3) (tracks: 5, 10)\nDesign – Stanislav Zakić\nLyrics By – Bane Opačić (tracks: 2, 4, 6, 11, 13, 14, 15, 17), Jelena Trifunović (tracks: 5, 7, 10), Marina Tucaković (tracks: 8, 18)\nMastered By – Streaky\nMusic By – Bane Opačić (tracks: 2, 6, 11, 13, 15, 17), Bojan Vasić (2) (tracks: 8, 10), Miloš Vuksanović (tracks: 4, 11, 14)\nPhotography By – Miloš Nadaždin`,
  },
  {
    albumId: 4,
    id: 47,
    name: "Bosanka",
    spotify: "",
    deezer: "",
    apple: "",
    youtube: "https://youtu.be/mPlhWClaqsE?si=Ik8iqM6rIo9YSH-Q",
    isActive: false,
    lyrics: `Sjeti se, ljubavi stara\ngodina njeznih i nevinih\nsjeti se najljepsih dana\ni kad sam ti prvi napisao stih\nSjeti se svih obecanja\nneka su zakletve i istine bile\nja sam jos tvoj\nto godine nisu promjenile\nRef.\nNocas pjevam o ljubavi\njedna si bila\nmoja i nicija tako\ngdje si se od mene skrila\nprelijepa Bosanko\nLjubavi moja si bila\nmoja i nicija tako\ngdje si se od mene skrila\nprelijepa Bosanko\nRef.`,
    credits: `Arranged By – Alek Aleksov (tracks: 1, 2, 6, 9, 11, 13, 15, 17), Dušan Alagić (tracks: 3, 4, 7, 8, 14), Marko Cvetković (3) (tracks: 5, 10)\nDesign – Stanislav Zakić\nLyrics By – Bane Opačić (tracks: 2, 4, 6, 11, 13, 14, 15, 17), Jelena Trifunović (tracks: 5, 7, 10), Marina Tucaković (tracks: 8, 18)\nMastered By – Streaky\nMusic By – Bane Opačić (tracks: 2, 6, 11, 13, 15, 17), Bojan Vasić (2) (tracks: 8, 10), Miloš Vuksanović (tracks: 4, 11, 14)\nPhotography By – Miloš Nadaždin`,
  },
  {
    albumId: 4,
    id: 48,
    name: "Tvoja Je Svaka Noć",
    spotify: "",
    deezer: "",
    apple: "",
    youtube: "https://youtu.be/xCOi3tpjb-M?si=d8IVsQrYV01CRpA8",
    isActive: false,
    lyrics: `Bila si lijepa k'o u nekom stranom filmu\ni vjerovao nisam da ces biti moja\nal' odozgo onaj tada mi namignu\ni sve crno predje u milion boja\nAl' vrlo brzo prava istina se javi\nda sem ljepote, duso, nemas ti nista\nvolis samo pare i prolazne stvari\nza tvoj avion vise nisam dobra pista\npa places jer ne znas sta ces\nkako bez tebe ja da se snadjem\nRef.\nIdi slobodno, tvoja je svaka noc\nbilo je naporno biti sa tobom\nja sam odlicno, vece je carobno\nma samo pusti mi nesto narodno\nBili smo srecni nekih mjesec i po dana\ni zivio sam, mili Boze, k'o u bajci\nal' primjetih ipak, to mi je mana\nda ti si vrlo budna dok ja sve to sanjam\nLjubav je camac sto po mutnoj rijeci plovi\ni ne mogu s tobom pricati o sreci\ntreba mi ruka sto me drzi i dok padam\na ti volis vise kad poklon je veci\npa places jer ne znas sta ces\nkako bez tebe ja da se snadjem\nRef. 3x`,
    credits: `Arranged By – Alek Aleksov (tracks: 1, 2, 6, 9, 11, 13, 15, 17), Dušan Alagić (tracks: 3, 4, 7, 8, 14), Marko Cvetković (3) (tracks: 5, 10)\nDesign – Stanislav Zakić\nLyrics By – Bane Opačić (tracks: 2, 4, 6, 11, 13, 14, 15, 17), Jelena Trifunović (tracks: 5, 7, 10), Marina Tucaković (tracks: 8, 18)\nMastered By – Streaky\nMusic By – Bane Opačić (tracks: 2, 6, 11, 13, 15, 17), Bojan Vasić (2) (tracks: 8, 10), Miloš Vuksanović (tracks: 4, 11, 14)\nPhotography By – Miloš Nadaždin`,
  },
  {
    albumId: 4,
    id: 49,
    name: "Dobro Mi Došla",
    spotify: "",
    deezer: "",
    apple: "",
    youtube: "https://youtu.be/3ycIkGALHqo?si=EJ2lXVdEijZVnuBr",
    isActive: false,
    lyrics:
      '`Ko je ko, ko je gdje\nto odavno nije bitno\nodavno nije bitno\nDa si tu kao prije\nsamo to je sada hitno\nto je sada hitno\nsamo da me nisi ti\nzaboravila\nRef.\nOd oprostaja do oprostaja\nnekome tren, nekome vijek\nod zagrljaja do zagrljaja\nja malo sijed, ti ljepsa tek\ndobro mi dosla, ljubavi nikada prosla\nKo je s kim, ko je sam\nto odavno je svejedno\nodavno je svejedno\nSamo da docekam\nda smo kao nekad jedno\nkao nekad jedno\nda mi kazes "nisam te zaboravila"\nRef.\nRef. 2x`',
    credits: `Arranged By – Alek Aleksov (tracks: 1, 2, 6, 9, 11, 13, 15, 17), Dušan Alagić (tracks: 3, 4, 7, 8, 14), Marko Cvetković (3) (tracks: 5, 10)\nDesign – Stanislav Zakić\nLyrics By – Bane Opačić (tracks: 2, 4, 6, 11, 13, 14, 15, 17), Jelena Trifunović (tracks: 5, 7, 10), Marina Tucaković (tracks: 8, 18)\nMastered By – Streaky\nMusic By – Bane Opačić (tracks: 2, 6, 11, 13, 15, 17), Bojan Vasić (2) (tracks: 8, 10), Miloš Vuksanović (tracks: 4, 11, 14)\nPhotography By – Miloš Nadaždin`,
  },
  {
    albumId: 4,
    id: 50,
    name: "Sve Je Isto",
    spotify: "",
    deezer: "",
    apple: "",
    youtube: "https://youtu.be/5RXRm3Eu3xI?si=_mkpEOU6f7mDO5FH",
    isActive: false,
    lyrics: `Sa moga prozora pred svitanje\npoleti zelja do tvoga nekog grada\nima joj godina al' ista je\ni jos te znam i jos me znas\ncuvas snjeg da me docekas\ngledas vozove\nRef.\nSve je isto kao kad si ovdje bila\nsamo sjecanja mi stare\npa se pitam da l' si nekog ostavila\nil' si sretnija il' si vjernija\nSve je isto kao kad si ovdje bila\nsamo srce nekad stane\nkad se pita da l' si me zabravila\nil' si ona kap od mora vjernija\nNa tvojim usnama da l' osvanu\njos slova imena mog k'o, draga, tad\nljubavi dodju al' ne ostanu\ni jos te znam i jos me znas\ncuvas snjeg da me docekas\ngledas vozove\nRef. 2x`,
    credits: `Arranged By – Alek Aleksov (tracks: 1, 2, 6, 9, 11, 13, 15, 17), Dušan Alagić (tracks: 3, 4, 7, 8, 14), Marko Cvetković (3) (tracks: 5, 10)\nDesign – Stanislav Zakić\nLyrics By – Bane Opačić (tracks: 2, 4, 6, 11, 13, 14, 15, 17), Jelena Trifunović (tracks: 5, 7, 10), Marina Tucaković (tracks: 8, 18)\nMastered By – Streaky\nMusic By – Bane Opačić (tracks: 2, 6, 11, 13, 15, 17), Bojan Vasić (2) (tracks: 8, 10), Miloš Vuksanović (tracks: 4, 11, 14)\nPhotography By – Miloš Nadaždin`,
  },
  {
    albumId: 4,
    id: 51,
    name: "Nema Šanse",
    spotify: "",
    deezer: "",
    apple: "",
    youtube: "https://youtu.be/UvTUgjFwuDE?si=SNOcpzeVzuujmALe",
    isActive: false,
    lyrics: `Pijemo sve do jutra\nokolo lijepe zene\nsvuda je guzva, a ja sam\nJer uvijek svane sutra\ni case polomljene\nti nisi medju njima znam\nSve druge lahko slazem\nda vise nisi bitna\npa usne bilo kojoj dam\nNekad na cetiri noge\nnekad me nosi hitna\nznas me u svemu pretjeram\nA ja ludujem, poljubim za dan\nnikom drugu sansu ne ostavljam\na u nedjelju, kad ustanem sam\nnema sanse, nema da se tebe ne sjecam`,
    credits: `Arranged By – Alek Aleksov (tracks: 1, 2, 6, 9, 11, 13, 15, 17), Dušan Alagić (tracks: 3, 4, 7, 8, 14), Marko Cvetković (3) (tracks: 5, 10)\nDesign – Stanislav Zakić\nLyrics By – Bane Opačić (tracks: 2, 4, 6, 11, 13, 14, 15, 17), Jelena Trifunović (tracks: 5, 7, 10), Marina Tucaković (tracks: 8, 18)\nMastered By – Streaky\nMusic By – Bane Opačić (tracks: 2, 6, 11, 13, 15, 17), Bojan Vasić (2) (tracks: 8, 10), Miloš Vuksanović (tracks: 4, 11, 14)\nPhotography By – Miloš Nadaždin`,
  },
  {
    albumId: 4,
    id: 52,
    name: "Ti Nevoljo Moja",
    spotify: "",
    deezer: "",
    apple: "",
    youtube: "https://youtu.be/bWOaWexYnZE?si=F_7_s85CnbaZ3juf",
    isActive: false,
    lyrics: `Dusa me zaboli kad ime cujem ti\na oko mene znaju svi kako me boli\na ti se pojavis i nasmijana sva\nna ranu svojim rukama utrljas soli\n\nJavim se glasom punim\nal' samo dobro glumim\nkad vidim te stane moj svet\nI srce mi zadrhti\nu glavi se zavrti\nsto nismo jedno, to je greh\n\nRef. 2x\nI ja i ti se patimo\na vreme bi da vratimo\na dani predugi su\nma nema im broja\n\nOboje s uma smetnemo\nkada se negde sretnemo\njer jos za tobom patim\nti nevoljo moja\nti nevoljo moja\n\nDani bez tebe tako sporo prolaze\na ja jos brojim poraze i uvjek kasnim\nu svakoj boci nadjem nove pouke\na trazim tvoje poruke da puknem sasvim\n\nJos glumim da sam jaka ali iz ovog mraka\nbez tebe necu moci, znaj\ni pravimo se vazni ja i moj osmeh lazni\na sve bih htela da ti dam\n\nRef. 2x`,
    credits: `Arranged By – Alek Aleksov (tracks: 1, 2, 6, 9, 11, 13, 15, 17), Dušan Alagić (tracks: 3, 4, 7, 8, 14), Marko Cvetković (3) (tracks: 5, 10)\nDesign – Stanislav Zakić\nLyrics By – Bane Opačić (tracks: 2, 4, 6, 11, 13, 14, 15, 17), Jelena Trifunović (tracks: 5, 7, 10), Marina Tucaković (tracks: 8, 18)\nMastered By – Streaky\nMusic By – Bane Opačić (tracks: 2, 6, 11, 13, 15, 17), Bojan Vasić (2) (tracks: 8, 10), Miloš Vuksanović (tracks: 4, 11, 14)\nPhotography By – Miloš Nadaždin`,
  },
  {
    albumId: 4,
    id: 53,
    name: "Cvijeće",
    spotify: "",
    deezer: "",
    apple: "",
    youtube: "https://youtu.be/-YwGuojSizI?si=QMapv4nVr3BUmetO",
    isActive: false,
    lyrics: `Dani idu, dani putuju\nneki srecni, neki tuguju\nda li tvoji zamnom tuguju?\n\nNoci zure, noci skitaju\nusne ljube i ne pitaju\nkoga ljube i ne pitaju\n\nHej dal bez mene\nisto cvjeta cvijece isto vene?\nHej dal te nocu\nnekad iz sna bude uspomene?\nKao mene zbog tebe\n\nNoci zure, noci nestaju\nusne ljube i ne prestaju\ndruge ljube i ne prestaju\n\nHej dal bez mene\nisto cvjeta cvijece isto vene?\nHej dal te nocu\nnekad iz sna bude uspomene?\nKao mene zbog tebe\nKao mene zbog tebe\n\nIde zivot godina po godina\ndodju ljubavi ni jedna sudjena\nima gradova ni jedan nije dom\nni jedno srce srcu mom\nni jedno srce srcu mom\n\nHej da l bez mene\nisto cvjeta cvijece isto vene?`,
    credits: `Arranged By – Alek Aleksov (tracks: 1, 2, 6, 9, 11, 13, 15, 17), Dušan Alagić (tracks: 3, 4, 7, 8, 14), Marko Cvetković (3) (tracks: 5, 10)\nDesign – Stanislav Zakić\nLyrics By – Bane Opačić (tracks: 2, 4, 6, 11, 13, 14, 15, 17), Jelena Trifunović (tracks: 5, 7, 10), Marina Tucaković (tracks: 8, 18)\nMastered By – Streaky\nMusic By – Bane Opačić (tracks: 2, 6, 11, 13, 15, 17), Bojan Vasić (2) (tracks: 8, 10), Miloš Vuksanović (tracks: 4, 11, 14)\nPhotography By – Miloš Nadaždin`,
  },
  {
    albumId: 4,
    id: 54,
    name: "Ljubav Preko Žice",
    spotify: "",
    deezer: "",
    apple: "",
    youtube: "https://youtu.be/3TuGoOc2fj0?si=9DOjuWnSRXO66TVW",
    isActive: false,
    lyrics: `Cekam dugo tvoj poziv\nneizvjesnost ima kraj\nljubav preko zice\nunaprijed izgubljen raj\n\nLetim avionom\nnije protiv nas\nu svakom brzom vlaku\nostavi poneku vlas\n\nRef.\nNapisi zvucno pismo\nslikaj se samo za moju dusu\ndaj mi njezan poljubac\ndaj mi ljubav preko zice\n\nTelegrami jure\npogresna adresa, broj\numoran jel' tuzan\nu glavi sumnjiv roj\n\nIluzija nema\nistinu odavno znam\nljubav preko zice\nna kraju ostajem sam\n\nRef.\n\nRef.`,
    credits: `Arranged By – Alek Aleksov (tracks: 1, 2, 6, 9, 11, 13, 15, 17), Dušan Alagić (tracks: 3, 4, 7, 8, 14), Marko Cvetković (3) (tracks: 5, 10)\nDesign – Stanislav Zakić\nLyrics By – Bane Opačić (tracks: 2, 4, 6, 11, 13, 14, 15, 17), Jelena Trifunović (tracks: 5, 7, 10), Marina Tucaković (tracks: 8, 18)\nMastered By – Streaky\nMusic By – Bane Opačić (tracks: 2, 6, 11, 13, 15, 17), Bojan Vasić (2) (tracks: 8, 10), Miloš Vuksanović (tracks: 4, 11, 14)\nPhotography By – Miloš Nadaždin`,
  },
  {
    albumId: 5,
    id: 55,
    name: "Lavovi",
    spotify:
      "https://open.spotify.com/track/5FPiQQLBfvGum0imLbW0Jr?si=e0051d886d16441d",
    deezer: "https://deezer.page.link/DBdZknFQdhKs8qzu8",
    apple: "https://music.apple.com/us/album/lavovi/1735316919",
    youtube: "https://youtu.be/JCPfEkttUK4?si=hXNS9rnuOl6c7Rb6",
    isActive: false,
    lyrics: `Opet, kao lavovi\n\nSvaki svetac ima svoju proslost\ni svaki gresnik ima svoj kraj\nrek´o sam dacu sto posto\na sad znam da nisam jak\n\nJer, danas tu ne pomaze doktor\nkad mrak u grudima nadje svoj stan\nda l´ je to ljubav il´ otrov\nkad neka druga ukrade ti san\n\nI bice bolja, ja to znam\nako odmah odem, bez povratka\n\nRef. kao lavovi\nme grizu sjecanja\ni sve na svijetu dao bih\nda tu si, gdje sam ja\n\nNije ljubav za mene\nod moga srca si daleko\nto su bile lazi sve\nu koje sam se kleo\n\nNekad poletim u noci\nnekad te nadjem u boci\nsamo kada cujem ti ime\npruzam ruke, vodi me\n\nRef. 2x\n\nTo su bile lazi sve\nu koje sam se kleo`,
    credits: `Muzika: Djordje Djordjevic, Ivan Obradovic\nTekst: Djordje Djordjevic, Ivan Obradovic\nAranzman: Alek Aleksov`,
  },
  {
    albumId: 5,
    id: 56,
    name: "Svirači",
    spotify: "",
    deezer: "",
    apple: "",
    youtube: "https://youtu.be/IyipgYVYdn4?si=xQG3E3fviExLyuyj",
    isActive: false,
    lyrics: `Ref.\nHajde, svirajte sviraci\nonu sto mi zivot znaci\nja cu opet naci nacin\nda vam zadnju paru dam\n\nSamo svirajte sviraci\nneka refren bude jaci\nnoc da ostane u casi\na da svane bolji dan\n\nA yay, yay, yay, a yay, yay, yay\na yay, yay, yay, ona lijepa kao san\na yay, yay, yay, a yay, yay, yay\na yay, yay, yay, a ja nocu lutam sam\n\nOvo ovdje je od Boga dato\ncijele noci sjedi brat sa bratom\nna svako zasto, mojih deset zato\njer je samo ona ta\n\nCasa je i prazna i puna do pola\nnije bitno, leti sa stola\nu njoj se krije samo istina gola\n\nDa li negdje s nekim spava\nili mene ceka sama\nneka snovi budu java\nda joj sebe dam, da joj sebe dam\n\nRef. 2x`,
    credits: `Muzika: Stefan Cvijović\nTekst: Vuksan Bilanović, Stefan Cvijović\nAranzman: Marko Gluhaković, G.Ratković-Rale`,
  },
  {
    albumId: 5,
    id: 57,
    name: "Izgubljena Srećo",
    spotify: "",
    deezer: "",
    apple: "",
    youtube: "https://youtu.be/MsXwRmrl8W4?si=VfNj0gFWh6eEVC3A",
    isActive: false,
    lyrics: `Pamtim ja jos uvijek prve poglede\nosmijehe i nase prve poljupce\npamtim ja jos uvijek, da li pamtis ti\nmoja ljubavi\n\nPozeljele oci da te gledaju\nuspomene jos mi mira ne daju\nu dusi mi jedna suza kanula\ni tu ostala\nRef. 2x\nIzgubljena sreco, jos si ljubav moja\nona, sto u srcu, ostala mi samo\nali, ja cu naci svijet sto mi te krije\ni kunem se Bogom, vidimo se tamo\n\nSanjao sam opet, da smo ti i ja\nu kafani, s pjesmom, kao nekada\nsvirali nam nasi stari Cigani\nod svih najbolji\n\nPozeljele oci da te gledaju\nuspomene jos mi mira ne daju\nu dusi mi jedna suza kanula\ni tu ostala\n\nRef. 2x`,
    credits: `Muzika: VUXA\nTekst: Miladin Bogosavljevic\nAranzman: Lexington/ Marko Cvetkovic`,
  },
  {
    albumId: 5,
    id: 58,
    name: "Da Mi Je",
    spotify: "",
    deezer: "",
    apple: "",
    youtube: "https://youtu.be/ECe06OuL0nI?si=BcmVvLJfgGhEu4zZ",
    isActive: false,
    lyrics: `Ti si mlada, tvoje godine\npriznacu u propast vode me\nbarikada da ne dodirnem\ntvoje usne, ne mogu to ne\n\nPamet me zove, a srce tone\njer nema kome, a silno bi to htjelo\ni sve je problem, ti si van zone\nja gubim domet, ugasen telefon\nKad bi neko me k'o ti namamio\nda te izbijem iz glave manio\ni sve bih dao da me ne gadja\nda te izbrisem iz sjecanja\n\nRef. 2x\nDa mi je k'o ona da me voli neko\nda mi je al' ne da zivot to\nradije, na nju bih cijeli zivot cekao\nradije samo da budem s njom\n\nRef. 4x`,
    credits: `Muzika: Stefan Cvijovic i Alen Kozic\nTekst: Stefan Cvijovic i Ognjen Jovanov\nAranzman: Marko Cvetkovic`,
  },
  {
    albumId: 5,
    id: 59,
    name: "Nesanica",
    spotify: "",
    deezer: "",
    apple: "",
    youtube: "https://youtu.be/lu_NKnuAlk8?si=rtYFbFDkJwoVXPYj",
    isActive: false,
    lyrics: `Najbolje vidim, kad zazmurim\nu mraku sve je jasno k´o dan\ngdje ti sad zuris, a ja ne zurim\ndobro te znam, predosjecam\n\nTvoje godine, radoznale\na sreca neuhvatljiva\n´ko je bistrio vodu\na da talog ne podigne sa dna\nRef.\nKad pravis se, a ne spavas\nu pola san se prekine\nsvaka nesanica ima svoje ime\n\nKad s drugim me poredis\nsamu sebe povrijedis\nmolim te, kad se vratis\npazi da me ne probudis\n\nNajvise kazem kada cutim\ntad lazima se izgubi trag\nu toj tisini ljubav slutim\njer, jos sam tvome srcu drag\n\nTvoje godine radoznale\na sreca neuhvatljiva\n´ko je bitrio vodu\na da talog ne podigne sa dna\n\nRef.\n\nMolim te, kad se vratis\npazi da me ne probudis`,
    credits: `Muzika: Petar Stokanovic\nTekst: Petar Stokanovic\nAranzman: Alek Aleksov/ VUXA`,
  },
  {
    albumId: 5,
    id: 60,
    name: "Dajem Stoljeće Za Jedno Proljeće",
    spotify: "",
    deezer: "",
    apple: "",
    youtube: "https://youtu.be/NDTe8uL2t7I?si=dXoN-XVoaHNylzOk",
    isActive: false,
    lyrics: `Zavoljeh te jednog aprila\nu srcu si gnijezdo svila\nstalno mislim na to proljece\nvjerovao sam, vjecno trajat ce\n\nNije bilo vece radosti\nsad mi nema vece slabosti\nRef.\nDajem stoljece za ono proljece\njos i sada behar osjecam\nmoja radosti, moja slabosti\nkako mogu da se ne sjecam\n\nDaljem stoljece za ono proljece\nkad sam s tobom zvijezde pratio\nmoja radosti, moja slabosti\nrado bih te, Dana, vratio\n\nJos sanjam te, veselu i snenu\nniz usne mi kletva krenu\ntvoje ruke, krila leptira\nneka nikada drugi ne dira\n\nNije bilo vece radosti\nsad mi nema vece slabosti\n\nRef.\n\nRado bih te, Dana, vratio\nrado bih te tada vratio`,
    credits: `Muzika: Bane Vasić\nTekst: Mustafa Aganagić Eudisc\nAranžman: Bane Vasić`,
  },
  {
    albumId: 5,
    id: 61,
    name: "Idem Na Put",
    spotify: "",
    deezer: "",
    apple: "",
    youtube: "https://youtu.be/9HdVSGSjWac?si=yJlboC_qsykayEFn",
    isActive: false,
    lyrics: `Ne volim rastanke one sto traju\ngdje jedni odlaze, a drugi ostaju\nte rijeci oprastanja, kao zbogom zvuce\nbolje da sutra bude isto kao juce\nuz rijeci, vidimo se, uskoro\n\nU casu za sampanjac sipam vodu krisom\nda trijezan nazdravim i odem s prvom kisom\njer, cekaju me neki kilometri novi\nsnagu mi daju neostvareni snovi\nuz rijeci, vidimo se, uskoro\n\nRef.\nIdem na put, uvijek sam bio onaj nocni\nsto danju drijema, a uvece sam super mocni\nu sali, nek´ me ne´ko prozove i pecne\ngdje si ti krenuo najgori od sve djece\n\nIdem na put da, tu smo, i na vezi smo\nma, gdjegod da smo nikad blizi nismo\nma, lako za veselje, al´ ako lose krene\ndrugovi moji racunajte na mene\n\nNe volim rastanke, slute na tugu\nzato, sve najbolje pozelite svom drugu\ni mirno more i uvijek lijepo vrijeme\nma, daj da nazdravimo i neka pjesma krene\nuz rijeci, vidimo se, uskoro\n\nRef.\n\nDrugovi moji, racunajte na mene`,
    credits: `Muzika: Petar Stokanović\nTekst: Petar Stokanović\nAranžman: Bane Vasić\n\nHarmonika: Bane Vasić\nGitare: Petar Trumbetaš\nPrateći vokali: Aleksandra Dabić\n\nMiks i master: Lazar Milić Laki`,
  },
];
